name: Authenticate to GitHub Packages (npm)
description: Adds the provided authentication token to the npm global configuration file.

inputs:
  token:
    description: The authentication token to be used.
    required: true
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Add authentication token
      shell: sh
      run: |
        cat << EOF > $HOME/.npmrc
          //npm.pkg.github.com/:_authToken=${{ github.token }}
        EOF
