version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "01:40"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "01:40"
