name: Add Dependabot changeset

on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  add-changeset:
    name: Add changeset
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    env:
      CHANGESET_FILE: ./.changeset/${{ github.run_id }}-${{github.run_attempt}}.md
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check out pull request
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr checkout ${{ github.event.pull_request.number }}

      - name: Setup pnpm (version 8)
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js (version 20)
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Authenticate to GitHub Packages (npm)
        uses: ./.github/actions/auth-github-packages/

      - name: Install dependencies
        run: pnpm install

      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1

      - name: Create changeset
        run: |
          echo "---
          \"@${{ github.repository }}\": patch
          ---

          Update dependency \`${{ steps.metadata.outputs.dependency-names }}\` from version \`${{ steps.metadata.outputs.previous-version }}\` to version \`${{ steps.metadata.outputs.new-version }}\`" > ${{ env.CHANGESET_FILE }}

      - name: Format files
        run: pnpm run lint:write

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          (git commit -m "Add changeset" && git push) || echo "No changes made"
