name: Add Dependabot changeset

on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  add-changeset:
    name: Add changeset
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    env:
      CHANGESET_FILE: ./.changeset/${{ github.run_id }}-${{github.run_attempt}}.md
    steps:
      - name: Check out pull request
        run: gh pr checkout ${{ github.event.pull_request.number }}

      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1

      - name: Create changeset
        run: |
          echo "---
          '@${{ github.repository }}': patch
          ---

          Update dependency \`${{ steps.metadata.outputs.dependency-names }}\` from version \`${{ steps.metadata.outputs.previous-version }}\` to version \`${{ steps.metadata.outputs.new-version }}\`" > ${{ env.CHANGESET_FILE }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          (git commit -m "Add changeset" && git push) || echo "No changes made"
