name: Add Dependabot changeset

on: pull_request

jobs:
  add-changeset:
    name: Add changeset
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    env:
      CHANGESET_FILE: ./.changeset/${{ github.run_id }}-${{github.run_attempt}}.md
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1

      - name: Create changeset
        run: |
          printf "---
          '@%s': patch
          ---

          Update dependency \`%s\` from version \`%s\` to version \`%s\`" "${{ github.repository }}" "${{ steps.metadata.outputs['dependency-names'] }}" "${{ steps.metadata.outputs['previous-version'] }}" "${{ steps.metadata.outputs['new-version'] }}" > ${{ env.CHANGESET_FILE }}

      - name: Show changeset
        run: cat ${{ env.CHANGESET_FILE }}
