name: Add Dependabot changeset

on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  add-changeset:
    name: Add changeset
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    env:
      CHANGESET_FILE: ./.changeset/${{ github.run_id }}-${{github.run_attempt}}.md
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1

      - name: Create changeset
        uses: generates/changeset-action@v3.0.0
        with:
          summary: Update dependency (or dependencies) \`${{ steps.metadata.outputs.dependency-names }}\` from version \`${{ steps.metadata.outputs.previous-version }}\` to \`${{ steps.metadata.outputs.new-version }}\`.

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          (git commit -m "Add changeset for dependency updates" && git push) || echo "No changes found, not pushing"
