name: Add Dependabot changeset

on: pull_request

jobs:
  add-changeset:
    name: Add changeset
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    env:
      CHANGESET_FILE: ./.changeset/${{ github.run_id }}-${{github.run_attempt}}.md
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Generate UUID for changeset
        id: uuid
        uses: filipstefansson/uuid-action@v1

      - name: Create changeset
        run: |
          echo "---
          '@synulux/prettier-config': patch
          ---

          Update dependency `${{ steps.metadata.outputs.dependency-names }}` from version `${{ steps.metadata.outputs.previous-version }}` to version `${{ steps.metadata.outputs.new-version }}`" > ${{ env.CHANGESET_FILE }}

      - name: Show changeset
        run: cat ${{ env.CHANGESET_FILE }}
